package com.ngandroid.lib.parser;

/**
* Created by davityle on 1/15/15.
*/
public enum TokenType {
    MODEL_NAME,
    MODEL_FIELD,
    FUNCTION_NAME,
    FUNCTION_PARAMETER,
    TERNARY_QUESTION_MARK,
    TERNARY_COLON,
    OPEN_PARENTHESIS,
    CLOSE_PARENTHESIS,
    COMMA,
    ADDITION,
    KNOT,
    SUBTRACTION,
    KNOT_EQUALS,
    MULTIPLICATION,
    DIVISION,
    PERIOD,
    EQUALS_EQUALS, NUMBER_CONSTANT, RUBBISH, EOF
}
